### PR TITLE
fix: Typos

### PR DESCRIPTION
**Pull request by Vxatz**

### CODE REVIEW

**Review by smartcontracts — APPROVED** [review]
Thank you! Feel free to shoot me an eth address and I'll send you that contributor NFT :-)

**Comment by Vxatz** [comment]
> Thank you! Feel free to shoot me an eth address and I'll send you that contributor NFT :-)

Thank you for making your work public! Here is my address: 0x28235e7B8074dee59279f168d6Dd4F44f1596Cf0 :)

**Comment by smartcontracts** [comment]
I set up the collection on Optimism, just waiting for it to be added to quixotic.io so you can actually view it :-). I'll send your NFT as soon as that's ready.

**Comment by smartcontracts** [comment]
Just minted the first ones! Went for a zombie theme :shrug: Here's yours :-) https://quixotic.io/asset/0x07810385aa29aF1fE6c89f14b2D810954aC78dF8/0

**Comment by Vxatz** [comment]
Thanks! :D

**Pull request merged**
