### PR TITLE
fix: small word corrections

### PR DESCRIPTION
**Pull request by NotPeopling2day**
A few more small word corrections

### CODE REVIEW

**Review by smartcontracts — APPROVED** [review]
Amazing, thank you! For future reference, it should be good enough to just edit the English version, the zh-CN version will update automatically with any updates to the English version.

**Comment by smartcontracts** [comment]
I've decided I'm going to send people one NFT for each contribution instead of just one NFT per user. Can I use the same address as before?

**Comment by NotPeopling2day** [comment]
Yep, NotPeopling2day.eth works for me. Thanks again!

**Comment by smartcontracts** [comment]
And here's number two https://quixotic.io/asset/0x07810385aa29aF1fE6c89f14b2D810954aC78dF8/4

**Pull request merged**
