### PR TITLE
fix: math for byte prefix in PoW

### LINKED ISSUE #1: Fix math issue in open-access section
Noticed this bug, bytes have 256 possible values not 16. Nibbles have 16 possible values. Either need to change the language to refer to nibbles or update the math. I personally think updating the math is cleaner, more people know about bytes than nibbles: https://github.com/smartcontracts/eth2-book/blob/467e1393fe861cb956e4db785532e8bdb66a92d5/src/book/02__blockchains/02__open-access.md?plain=1#L45

### PR DESCRIPTION
**Pull request by rootulp**
Fixes https://github.com/smartcontracts/eth2-book/issues/1

Thanks for publishing this book!

### CODE REVIEW

**Review by smartcontracts — APPROVED** [review]
Way better than the previous version, thank you! Feel free to drop an ETH address here and I'll send you a contributor NFT when I get around to drawing them tomorrow :-)

**Comment by rootulp** [comment]
That's so cool! My ENS is rootulp.eth - I really appreciate it. 

On a related note, soon there will be a service that makes it easier for maintainers to give contributors POAPS: https://gitpoap.io/

**Comment by smartcontracts** [comment]
Ooo that's super cool, I'd love to try it out for the optimism monorepo!

**Comment by smartcontracts** [comment]
Also, here ya go! Thank you again! https://quixotic.io/asset/0x07810385aa29aF1fE6c89f14b2D810954aC78dF8/2

**Comment by rootulp** [comment]
> Ooo that's super cool, I'd love to try it out for the optimism monorepo!

Tagging @colfax23 @jaypb1 for awareness. Optimism 🤝 GItPOAP would be dope

**Comment by colfax23** [comment]
Let’s do it! Drop the repo in here and I’ll follow up with you tomorrow :)

https://gitpoap.io/#suggest

**Comment by rootulp** [comment]
Done 👍 @smartcontracts you may also want to suggest it as a repo owner

**Comment by smartcontracts** [comment]
Submitted!

**Pull request merged**
