### PR TITLE
Changed "forward" to "foreword" in filename, config, and title

### PR DESCRIPTION
**Pull request by avras**
I think "Forward" should be "Foreword" in the title of `book/00__introduction/00__forward.md`.

- Renamed `00__forward.md` to `00__foreword.md`.
- Incorporated same change in `config.js` and `index.md`. 
- Tested with `npm run build` and `npm run dev`

### CODE REVIEW

**Review by smartcontracts — APPROVED** [review]
Haha, oops. Thank you!

**Comment by smartcontracts** [comment]
Shoot me an ETH address and I'll make you an NFT :-)

**Comment by avras** [comment]
0x3081b6978f7374e6427Db8b78dA2985b6C5D6483
It will be my first ever NFT :)

**Comment by smartcontracts** [comment]
I set up the collection, just waiting for it to be added to quixotic.io and I'll start sending the NFTs out, thank you again! https://github.com/smartcontracts/eth2-book-nfts

**Comment by smartcontracts** [comment]
Alrighty, collection is set up! Sent it over :-) https://quixotic.io/asset/0x07810385aa29aF1fE6c89f14b2D810954aC78dF8/1

**Comment by avras** [comment]
Thanks for the NFT. Also, thanks for sharing the eth-book-nfts repo. I might try it out myself on Optimism (mint some NFTs for my course TAs).

**Comment by avras** [comment]
I forked your eth2-book-nfts repo and managed to mint NFTs for my course TAs. Thanks!
Collection: https://quixotic.io/collection/ee337-instructors
https://github.com/avras/ee337-nfts has the fork, in case someone wants to see what changes are required to your original code.

**Pull request merged**
